### ISSUE TITLE
Some png images cause watchapp to crash

### ISSUE THREAD

**Issue by PhilipDodson** [pebble-examples/pebble-faces#8]
Branch: features/use-upng

  "http://phpqrcode.sourceforge.net/img/qrcode.png" - this image caused the watchapp to crash
  "http://www.mypebblefaces.com/files/2113/6635/6148/FakeQR-144.png" - this image displayed fine on the watchapp (however, it could not be scanned, likely due to no border on bottom side)

**Comment by vedantmehta99** [comment]
The bug is still not fixed, i don't believe.

**Comment by sarfata** [comment]
The image you are trying to load is a 32 bit true color png. Please see the "Preparing images" section in the README to prepare a black and white image.

Pebble 3.0 has much better png loading and error reporting. This will come to the original Pebble in the next few months.
